### ISSUE TITLE
overrideAir > 4.0.0 does not work with VKontakte extension for Adobe AIR (iOS & Android)

### ISSUE THREAD

**Issue by denisgl777** [myflashlab/ANE-LAB#11]
I use this library to work with the social network vkontakte
https://github.com/marpies/vk-ane
the use of any override > 4.0.0 library does not allow the library vk
When using ane lab, I have to constantly replace the override library
I need to ask on the side of the developers of this library of some updates?

**Comment by myflashlab** [comment]
We have a blog post explaining how other ANE developers can implement the overrideAIR ANE in their projects to avoid such conflicts. the post is here: https://www.myflashlabs.com/efficiently-override-native-methods-air-native-extensions/

**Notice:** The latest version of overrideAIR is required or the ANEs being installed using ANELAB won't work.

in MyFlashlabs, our goal is to free the mind of developers when it comes to native use. developing a VKontakte air native extension is in our to-do list. can't tell **when** however!
