### ISSUE TITLE
UNABLE TO REGISTER ANE's IN ANELAB

### ISSUE THREAD

**Issue by Gokulv617** [myflashlab/ANE-LAB#124]
![Screenshot_20201104-152335_Halloween 2020](https://user-images.githubusercontent.com/43432782/98099726-ec75f780-1eb5-11eb-8eb9-2096b1119f48.jpg)
**Someone please tell me the procedure to register ANE's**

_STEPS I FOLLOWED,_
1.	Logged to my account in ANELAB – Successfully logged in
2.	Created a new project
3.	Added all required ANE’s in ANELAB
4.	Clicked register ANE’s button
5.	Synced the project
6.	Added all ANE’s downloaded via ANELAB to my project in ANIMATE
7.	Published apk
8.	Deployed in physical device – Shows the ANE I’m using is DEMO version

**Comment by applauzmedia** [comment]
Did you find a fix for this? I'm having the same problem with the FCM ANE.  The only place I;ve got this ANE is from ANE Lab after registering it.
