### ISSUE TITLE
Permissions ANE Demo Popup

### ISSUE THREAD

**Issue by chrslgr** [myflashlab/ANE-LAB#129]
Hi,
I have acquired your Permissions ANE some time ago - back then it was version 3.0.
I have updated now to 5.0, but both on Android and iOS I now get a message in the built app that I would use a demo ane. 

Please help, the ane is implemented in a live product of us and that does not look good to our customers! 

Thanks,
Chris

**Comment by Gokulv617** [comment]
@chrslgr 
You should register the ANE's before syncing from ANE LAB. After you register, the XML will contain a a new tag like below
<meta-data android:name="com.myflashlabs.aneLab.id"android:value="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"/>
**You should use this tag in the project XML to avoid demo ANE popup inside the project**

![img_20201229](https://user-images.githubusercontent.com/43432782/103258819-c738cd80-49bc-11eb-9f9c-fc2f871750da.png)

**Comment by chrslgr** [comment]
Hi,

thanks for your reply, but it's not a solution to my problem. I'm not Club-member, but purchased the ANE only.
So here is a screenshot of my order - with no possibility to register the ANE. Please help, it is urgent!


Thanks,
Chris

**Comment by myflashlab** [comment]
@chrslgr individual ANEs don't have the demo dialog in them. are you sure you are using the correct ANE being downloaded from your myflashlabs account? please contact support for more talks and happy new year ^_^

**Comment by chrslgr** [comment]
well, your general contact form does not work, and if i click on contact tech support, i need to purchase a premium support package. that's the reason i contact you here.
and yes, i downloaded the ane directly from my order page.
urgent support required! 
it's not acceptable to buy a product and can't use it unless i buy a support package!
thanks,
chris

**Comment by myflashlab** [comment]
@chrslgr I just checked and confirm that the ANE available for download on our site is the correct version with no dialog. So if you are seeing the dialog, it must be from another ANE you might be using in your project. please let me know which other ANEs from us are you using? The other thing I can think of is that maybe your project is still loading another ANE version while you think the correct one is being used. This confusion happens all the time to best of us ^_^ And thanks for leting us know the contact form is not working... I was wondering why the incoming emails had stopped and then I thought maybe that because of the holidays! but it's not obviously. We'll fix that later on.

**Comment by chrslgr** [comment]
Well, I have a screenshot (attached) of the demo popup, which says "DEMO
ANE! The library 'com.myflashlab.air.extensions.permissionCheck' is not
registered!".
No, I don't use any other myflashlabs-ANE - just some of distriqt.
I have androidx.core.ane and overrideAir.ane integrated as required.
I wouldn't know where else to download this ane - I downloaded it from "My
Account > Orders".
I can send you the downloaded ane-file as well:
https://wetransfer.com/downloads/1594163fb0ac326405ece162974a9da220210104054055/d37986ae485cab646eba64c19a61f0ab20210104054112/c4c9b7

[image: IMG_1873.PNG]



On 30.12.2020, at 20:15, MyFlashLabs <notifications@github.com> wrote:


@chrslgr <https://github.com/chrslgr> I just checked and confirm that the
ANE available for download on our site is the correct version with no
dialog. So if you are seeing the dialog, it must be from another ANE you
might be using in your project. please let me know which other ANEs from us
are you using? The other thing I can think of is that maybe your project is
still loading another ANE version while you think the correct one is being
used. This confusion happens all the time to best of us ^_^ And thanks for
leting us know the contact form is not working... I was wondering why the
incoming emails had stopped and then I thought maybe that because of the
holidays! but it's not obviously. We'll fix that later on.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/myflashlab/ANE-LAB/issues/129#issuecomment-752728870>,
or unsubscribe

**Comment by myflashlab** [comment]
@chrslgr 
1. Please do not share licensed files on open forums.
2. The file you sent is identical to the correct one uploaded and it does not include the demo dialog. This is what I tested and can confirm for the second time.
3. the [contact form](https://www.myflashlabs.com/contact/) is fixed, you can use that to send over files.

If I were you I would had created a quick test app and added the ANEs into that project and compile and make sure what might be wrong.

I have to close this ticket, feel free to contact us back on the [contact form](https://www.myflashlabs.com/contact/).
