### ISSUE TITLE
ANE Lab freezes and not responding on my Windows 10

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/ANE-LAB#131]
May be you cann tell what logs / info I can add?

**Comment by myflashlab** [comment]
in your computer's myDocuments folder, you should be able to see error logs in `ANELAB_LOGS` dir.

**Comment by Gokulv617** [comment]
Same issue to me.. Recently most of the time ANELAB freezes and not responding on my windows 10. Then i delete _AppData\Roaming\com.myflashlabs.aneLab_ folder and again open it starts fresh. and it does not download the updated ANE's. There is some problem 
[logs.txt](https://github.com/myflashlab/ANE-LAB/files/5707198/logs.txt)

**Comment by myflashlab** [comment]
Interesting. Will have a closer look and try to see if I can duplicate this. Let me get back to you...

**Comment by Gokulv617** [comment]
I tried installing in my other Windows 10 PC, it opens but im not able to update the latest GoogleSignIn ANE. Indicates in green but nothing happens when I click to update.
![img_20201217](https://user-images.githubusercontent.com/43432782/102450724-18f86400-405d-11eb-9322-10b5a1d1c944.png)

**Comment by Gokulv617** [comment]
> I tried installing in my other Windows 10 PC, it opens but im not able to update the latest GoogleSignIn ANE. Indicates in green but nothing happens when I click to update.
> ![img_20201217](https://user-images.githubusercontent.com/43432782/102450724-18f86400-405d-11eb-9322-10b5a1d1c944.png)

Please give me a solution soon. I'm working in this project. Why I'm not able to update the ANE ? because of this issue GoogleSignIn ANE is not generated in the ANE folder. I'm stuck now

**Comment by Gokulv617** [comment]
> > I tried installing in my other Windows 10 PC, it opens but im not able to update the latest GoogleSignIn ANE. Indicates in green but nothing happens when I click to update.
> > ![img_20201217](https://user-images.githubusercontent.com/43432782/102450724-18f86400-405d-11eb-9322-10b5a1d1c944.png)
> 
> Please give me a solution soon. I'm working in this project. Why I'm not able to update the ANE ? because of this issue GoogleSignIn ANE is not generated in the ANE folder. I'm stuck now

is it fixed ?

**Comment by myflashlab** [comment]
Found the problem. we'll be fixing it a.s.a.p and let you know.

**Comment by myflashlab** [comment]
the newer update to google sign in should have fixed the problem. please check and let me know if you still see anything wrong.

**Comment by Gokulv617** [comment]
yes it is fixed now. thanks
