### ISSUE TITLE
Can't create icons on OSX.

### ISSUE THREAD

**Issue by roipeker** [myflashlab/ANE-LAB#15]
ANE LAB >> Icon Manager >> iOS, shows this error when generating the icon:
> xcrun: error: unable to find utility "actool", not a developer tool or in PATH

OSX High Sierra 10.13.3
XCode 9.2

xcrun is in my system PATH, actool is not.

**Comment by myflashlab** [comment]
Well, "actool" seems to be necessary. This error you are seeing is coming directly from your terminal. probably do some googling about that might help: https://www.google.com/search?client=firefox-b-ab&ei=zuCDWtOeLoWdkwWc4Ky4Ag&q=unable+to+find+utility+actool%2C+not+a+developer+tool+or+in+PATH&oq=unable+to+find+utility+actool%2C+not+a+developer+tool+or+in+PATH
