### ISSUE TITLE
Application Descriptor

### ISSUE THREAD

**Issue by llorenzo** [myflashlab/ANE-LAB#16]
Hey, I just don't get it. What do I have to put into the icon tag in the Application Descriptor .xml?
I tried this:
```
       <image40x40>AppIcon20x20@2x.png</image40x40>
        <image40x40>AppIcon20x20@2x~ipad.png</image40x40>
        <image60x60>AppIcon20x20@3x.png</image60x60>
        <image20x20>AppIcon20x20~ipad.png</image20x20>
        <image58x58>AppIcon29x29@2x.png</image58x58>
        <image58x58>AppIcon29x29@2x~ipad.png</image58x58>
        <image87x87>AppIcon29x29@3x.png</image87x87>
        <image29x29>AppIcon29x29~ipad.png</image29x29>
        <image80x80>AppIcon40x40@2x.png</image80x80>
        <image80x80>AppIcon40x40@2x~ipad.png</image80x80>
        <image120x120>AppIcon40x40@3x.png</image120x120>
        <image120x120>AppIcon60x60@2x.png</image120x120>
        <image180x180>AppIcon60x60@3x.png</image180x180>
        <image152x152>AppIcon76x76@2x~ipad.png</image152x152>
        <image167x167>AppIcon83.5x83.5@2x~ipad.png</image167x167>
        <image40x40>AppIcon40x40~ipad.png</image40x40>
        <image76x76>AppIcon76x76~ipad.png</image76x76>
```
But that doesn't compile. Image40x40 is not supported. I'm on IntelliJ.
Thanks

**Comment by mshaffer12882** [comment]
Should look more like this:
Your doubling some of your icons and don't seem to be the correct size.
<icon>
    <image29x29>assets/icons/icon29.png</image29x29>
    <image48x48>assets/icons/icon48.png</image48x48>
    <image50x50>assets/icons/icon50.png</image50x50>
    <image57x57>assets/icons/icon57.png</image57x57>
    <image58x58>assets/icons/icon58.png</image58x58>
    <image72x72>assets/icons/icon72.png</image72x72>
    <image87x87>assets/icons/icon87.png</image87x87>
    <image96x96>assets/icons/icon96.png</image96x96>
    <image100x100>assets/icons/icon100.png</image100x100>
    <image114x114>assets/icons/icon114.png</image114x114>
    <image128x128>assets/icons/icon128.png</image128x128>
    <image144x144>assets/icons/icon144.png</image144x144>
    <image180x180>assets/icons/icon180.png</image180x180>
  </icon>

**Comment by myflashlab** [comment]
please use this repository for general question related to the ANELAB software. Thanks.
