### ISSUE TITLE
I really don't want to use new inteface toy

### ISSUE THREAD

**Issue by CrazyFlasher** [myflashlab/ANE-LAB#19]
I have no time to play with it.
Can I build Firebase core 6.0.1 like before? I need to release app ASAP, because a lot of crashes

**Comment by myflashlab** [comment]
The core V6.0.1 is not yet released through the old ways. One of the main reasons we developed the ANELAB was to be able to release ANE updates fast.

It seems like you are in a big hurry. Please send us an email with your Json/plist and I’ll send you back the generated Firebase Core. We’d be happy to help.

**Comment by CrazyFlasher** [comment]
thanks. Where is can find your email?

**Comment by CrazyFlasher** [comment]
mail me please: anton@javelin.ee
plist and json are attached
[files.zip](https://github.com/myflashlab/ANE-LAB/files/1766206/files.zip)

**Comment by myflashlab** [comment]
Ok, just to be sure, your Android package name is ```ee.Javelin.SpotlightRoomEscape``` correct? Have you manually removed the initial ```air.``` yourself?

**Comment by CrazyFlasher** [comment]
yes I removed "air.". WE use `AIR_NOANDROIDFLAIR=true`

**Comment by CrazyFlasher** [comment]
btw, I think ANE-LAB is cool for most of developers, but we use our own dependency management system based on maven, so better for just to download zip with ANEs from time to time and update artifacts manually in our maven-repo

**Comment by myflashlab** [comment]
email sent. :)

**Comment by CrazyFlasher** [comment]
Thank you very much!
