### ISSUE TITLE
Everything resizes to full screen on open, I use a 4k screen, this is very annoying

### ISSUE THREAD

**Issue by pclinx** [myflashlab/ANE-LAB#2]

**Comment by myflashlab** [comment]
correct. This is already in our to-do list. as for now, we focused on the functionality rather than UI. When more features are added, we will also re-work the UI t look and function better. Thanks for your suggestion.

**Comment by myflashlab** [comment]
This problem is addressed with the upcoming V0.0.42... we'll release it soon.
