### ISSUE TITLE
Demo license message

### ISSUE THREAD

**Issue by 4malik** [myflashlab/ANE-LAB#20]
Hi. Today I used ANE LAB for my second project. I did everything like for the first project (it works).
All created successfully. But after launch I got alert:"This is DEMO. You are using the demo license of MyFlashlbas.com Products".
My license is from July 24, 2017.
In ANE Lab I correctly logged in. And I can't find why I got it.

![image](https://user-images.githubusercontent.com/30479942/37423240-c6ff9c8c-27d6-11e8-85ba-d495bb30132b.png)

after update libs(firebase core and override air) there is the same message.

**Comment by myflashlab** [comment]
After you finished adding the required ANEs, you should click on the big blue button "Export to Modify the manifest file".

**Comment by 4malik** [comment]
Thanks a lot. I clicked it, but maybe i did some changes after that and forgot.
All is working now. thanks. You can close this issue.
