### ISSUE TITLE
ANE LAB INSTALLER? 

### ISSUE THREAD

**Issue by PapaDeBeau** [myflashlab/ANE-LAB#21]
I am so new to this ANE-LAB installer thing. I get this error: 
This ANE is dependent on com.myflashlab.air.extensions.permissionCheck. Please install the missing ANE first and then try again.

**Comment by myflashlab** [comment]
This simply means you need to install the permissioncheck ANE first. in the same window where you are trying to add the ANE you want, type "permission" in the search box. then the permissioncheck ANE will show up. click on it and install that. Then try to add your other ANE.
