### ISSUE TITLE
Always shown Loading the project...

### ISSUE THREAD

**Issue by 4malik** [myflashlab/ANE-LAB#22]
I used prev version and it works fine.
Today i updated ANE LAB and tried to create new project. I added project data and then i got "Loading the project". I waited over one hour but the screen doesn't changed/ I totally removed all ANELab + data and tried again but result is the same.

**Comment by myflashlab** [comment]
please make sure you have updated to the latest version of the software and if you still have such problems, please open a new issue. Thanks.
