### ISSUE TITLE
UPDATE in projects 

### ISSUE THREAD

**Issue by pclinx** [myflashlab/ANE-LAB#3]
UPDATE button in Project identifies that updates are available and hover over note say "Update to VX.XX", but nothing happens if you press.

I may be miss-understanding, but with no documentation I cant tell

![croppercapture 222](https://user-images.githubusercontent.com/400080/33941611-24892616-e00b-11e7-9934-c8b9dbe7a5db.png)

**Comment by myflashlab** [comment]
more information on this please...
Which version of the software are you using?
Please use the update window to make sure you have the latest software first and then update the ANEs if there are any.

**Comment by pclinx** [comment]
V0.0.24 on Widows 7
Just updated to V0.0.25, checked for updates to ANEs
GPS is listed as V3.3.2 in ANE Explorer
In the project appears as above and hover over "UPDATE" button says "Update to V3.3.2" but pressing button does nothing

**Comment by myflashlab** [comment]
V3.3.2 for GPS is the latest version and the "update" button must not have shown to begin with. 🤔 try deleting the ANEs and add them back again to see what happens.

**Comment by pclinx** [comment]
Not sure I understand, the Project has V3.3.0 of GPS and the screen correctly identifies that the latest is V3.3.2, but does nothing if I press the button.
If I remove the ANEs and add them back again then they will be V3.3.2 etc. and will therefore not need updating?
I am not trying to fix the project, just how ANE LAB handles in need of updating!

**Comment by myflashlab** [comment]
aha, your project has V3.3.0... will you please send this specific version to us so maybe we can try to duplicate the bug?

**Comment by pclinx** [comment]
Attached simple test project (FlashBuikder fxp), If suit your needs let me know what you want.
The good news is that ANE LAB has allowed me to compile and run a project with MyFlashLab ANE for the first time, so am very keen to help on this.

[TestGPSANE_1.zip](https://github.com/myflashlab/ANE-LAB/files/1555804/TestGPSANE_1.zip)

**Comment by pclinx** [comment]
If you need the individual files, just rename fxp to zip and extract the files

**Comment by myflashlab** [comment]
Good cache! the update button does not work because the current ANE you are using is too old for the ANE-LAB software to recognize it.

ANE-LAB can only update those ANEs which are already optimized to be used with ANE-LAB. in simple terms, you can expect an ANE to be updated only if it has been installed with the ANE-LAB before.

the workaround is to delete it and install it back using the ANE-LAB.

However, I am writing this down so an appropriate dialog will open in similar cases.
