### ISSUE TITLE
Firebase Authentication gives an error "Compilation failed while executing : ld64"

### ISSUE THREAD

**Issue by denisgl7** [myflashlab/ANE-LAB#32]
Firebase Authentication Now requires installation Dynamic Links and Invites (It is necessary?)
When installing on iOS, an error occurs
Compilation failed while executing : ld64 
Air 32, Windows 10, iOS latest, Ane latest

**Comment by myflashlab** [comment]
This repository is only related to ANELAB software itself. for tech questions about ANEs you need to use our private/secure support platform. Thanks.
