### ISSUE TITLE
dx tool failed: UNEXPECTED TOP-LEVEL EXCEPTION: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

### ISSUE THREAD

**Issue by joyola** [myflashlab/ANE-LAB#33]
I can not generate the apk or run on my device using FlashBuilder.

<img width="622" alt="Screen Shot 2019-06-23 at 11 35 12" src="https://user-images.githubusercontent.com/4267418/59978374-09a47180-95b2-11e9-9d87-16be0225f5f6.png">

Any idea?

**Comment by myflashlab** [comment]
For ANE related questions, please use our private/secure premium support platform. Thanks.
