### ISSUE TITLE
Would be usefull to be able to drag ANE from ANE Exporer to Project window

### ISSUE THREAD

**Issue by pclinx** [myflashlab/ANE-LAB#4]
to add it and have it add all dependencies.

Again I might be miss-understanding usage due to no documentation.

**Comment by myflashlab** [comment]
to add new ANEs to your project, you won't be using the ANE explorer window. instead there is a button in your project which opens a new window showing all available ANEs. We currently think adding a search box at the top of that window would be more helpful.

Let me know if this will solve what you suggested?
