### ISSUE TITLE
cannot install   any clue?

### ISSUE THREAD

**Issue by etulfnap** [myflashlab/ANE-LAB#5]
![image](https://user-images.githubusercontent.com/1762095/33987449-de7cbf7e-e0fb-11e7-9084-8220c167c162.png)

I made sure only 1 installer is running.

**Comment by myflashlab** [comment]
We have changed the software certificate, you need to uninstall the old
version and then try to install the new one

**Comment by myflashlab** [comment]
So, were you able to install it? if it's not related to old/new certifications, maybe you would restart your computer to make sure an older installer is not running.

**Comment by etulfnap** [comment]
While installing the app, there's option for "create shortcut"  checkbox,  after I turn this off, I could install.
I have checked any preinstalled version or  there's no "C:\Program Files (x86)\ANE LAB"  folder  before installation.  I tried restart and install again, but had same problem as prior post.
Whoever have same problem as me, please try to uncheck "create shortcut".
