### ISSUE TITLE
Problems recognising SDK's

### ISSUE THREAD

**Issue by pclinx** [myflashlab/ANE-LAB#6]
Still having problems getting it to recognise SDKs
Its working recognising AIR26 but not AIR27 or AIR28

![recognisesdk](https://user-images.githubusercontent.com/400080/33990459-f73e935e-e0c2-11e7-989d-f15cfea76990.png)

**Comment by myflashlab** [comment]
The folder which you choose as your AIR SDK must have the **air-sdk-description.xml** at the root of its path. This file is always present in any AIR SDK package as far as we know. ANELAB reads this file to know the selected AIR SDK version. Please verify if the folder you are selecting includes this file or not.

**Comment by pclinx** [comment]
pclinxAdmin

**Comment by myflashlab** [comment]
I see. Glad it works now, but anyway, can you please send me a screenshot of the available files/directories in your SDK when using Apache Flex Installer? maybe we can make it work with that also in future releases.

**Comment by myflashlab** [comment]
still waiting on this... Thanks.

**Comment by myflashlab** [comment]
Closing the issue because of no response. However, we'd be happy to reopen it when more information is provided.
