### ISSUE TITLE
updates not working

### ISSUE THREAD

**Issue by etulfnap** [myflashlab/ANE-LAB#7]
I love the concept of this program, as I'm one of the users always had headache to set these ANEs up.
Thank you for sharing such a handy application.  :)
Before ask current issue I'd like to be clear about the below.
1. Do I need to download all the ane separately and copy to somewhere ?
2. Right now there's nothing in "Browse ANEs" under "ANE Lab".  Do I need to update first in order to see any list?

![image](https://user-images.githubusercontent.com/1762095/34045565-69c539ce-e1e4-11e7-94a3-6bdac79413d1.png)

![image](https://user-images.githubusercontent.com/1762095/34045061-6bacc808-e1e2-11e7-86e1-652626703c23.png)

Any suggested workarounds?  Waited around 30minutes, still nothing..

**Comment by myflashlab** [comment]
usually the first time is the most heavy time :) after the first update, you'll receive updates more easily. 

If your download is not working, check out your internet connection. It's a big download task so it's normal to take a while if you are on a slow connection.

**Comment by myflashlab** [comment]
> Do I need to download all the ane separately and copy to somewhere ?

No, no copy pasting at all. the software will take care of it all.

**Comment by etulfnap** [comment]
Thanks for prompt feedback.
About the internet speed, my line can download 2Gb video file from Vimeo in 5 minutes. 
Downloading whole membership package from Myflashlab also won't take this long time.
I turned on several hours now, and still nothing.
I allowed AneLab in my filrewall, I tried run as admin, and turn on update and left for hours also same result.  Any other workaround that I can try?

**Comment by myflashlab** [comment]
Well, I have no idea why the downloads don't start on your computer! ANEs are hosted by GitHub and no one else seems to have a similar problem with the download part.

Anyway, we have added the following to our to-do list:   
**Feature:** Log errors in a .txt file so we can better debug and improve the software.

**Comment by etulfnap** [comment]
Adding Logging feature will be great.   How about let users can download whole package file and install manually?   Too bad just because of downloading problem, I can't use it.

**Comment by myflashlab** [comment]
manual installation is also a good idea. we'll put that in our to-do list. thanks for suggesting that.

Yet, I am puzzled why the downloads does not work for you. Tell me if you have been able to login to your club membership within the app already? If you can't download the packages and you can't login, it means that the software cannot connect to internet for some reason.

**Comment by etulfnap** [comment]
Thanks a lot keep follow this post up.

Yes. I logged in with membership account. 
 As you may see my screen capture above, "silver 1 developer"  only appears after I log in.
Also, getting update list  I assume those are coming from online, are they? 

By the way, I'm using windows 10 (home insider preview  Build 17946), and air 28.  I reinstalled windows and turned off all firewall, lowered all IE security setting, and allowed apps from anywhere.

Also I tried with osx, ANELab worked properly.  So... I guess there's no intenal network problem.
Maybe window release version too recent? 

I checked localStrorage as well.  It seems file creation was ok, but somehow download stream stop.
![image](https://user-images.githubusercontent.com/1762095/34078743-3c7b8c52-e35b-11e7-872d-aa46e960b1f8.png)

**Comment by myflashlab** [comment]
Well, considering that the location we are using is ```applicationStorageDirectory``` and this location is writable by AIR as mentioned in the documentations, my guess is that the problem should be with the "home insider preview" version of windows that you are using. Maybe that builds are not allowing AIR to write correctly to those locations. I think this could be something that Adobe or Microsoft should address.

**Comment by etulfnap** [comment]
I roll back to old windows.  as you guessed, it works well! 
Thanks for help!

**Comment by myflashlab** [comment]
Ok, good, anyhow, we just released V0.0.26 which includes the log-printing thing...
